spring:
  application:
    name: icloud_gateway
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    iuc:
      path: /iuc/**
      sensitiveHeaders:
    ifile:
      path: /ifile/**
      sensitiveHeaders:
    icloud_gateway:
      path: /self/**
      sensitiveHeaders:
server:
  port: 8000
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000